# Generated by Django 5.0 on 2024-01-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name': 'University Campus'},
        ),
    ]
