# Generated by Django 5.0 on 2024-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdrawl', 'Withdrawl'), ('Deposit', 'Deposit')], max_length=10),
        ),
    ]
